[package]
name = "nova_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2"
boa_unicode = "0.16.0"
phf = { version = "0.11", features = ["macros"] }
