[package]
name = "nova_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = { version = "0.4", features = ["derive", "nightly"] }
wtf8 = "0.1"
oxc_parser = "0.0.6"
oxc_ast = "0.0.6"
hashbrown = "0.13"
string-interner = "0.14.0"
