[package]
name = "nova_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3", features = ["derive"] }
oxc_parser = "0.0.6"
oxc_ast = "0.0.6"
nova_vm = { path = "../nova_vm" }
